connection:
  retry_timeout: 1.0
udp_connection:
  device_port_dp: 2368
  device_port_pp: 8308
sensor:
  buffer_capacity: 100000
  min_distance: 0.05
  max_distance: 100.0
  device_name: "Velodyne HDL-32E"
  data_packet_publish: "data_packet"
diagnostics:
  dp_min_freq: 10.0
  dp_max_freq: 200.0
  pp_min_freq: 0.1
  pp_max_freq: 100.0
ros:
  queue_depth: 100
  frame_id: "vehicle_velodyne_link"
